import { SETTINGS_THEME } from "../core/features/storage/localStorageKeys";
import LocalStorageManager from "../core/features/storage/localStorageManager";
import type { ThemeValues } from "../types/settingsTypes";

/**
 * Handles settings-related management
 */
class SettingsApp {
	private static instance: SettingsApp | null = null;

	/**
	 * Theme generated by default
	 */
	private readonly DEFAULT_THEME: ThemeValues = "system";

	private localStorage: LocalStorageManager;

	private constructor() {
		this.localStorage = new LocalStorageManager();

		this.generateDefaults();
	}

	/**
	 * @returns singleton instance of {@linkcode SettingsApp}
	 */
	public static getInstance(): SettingsApp {
		return (SettingsApp.instance ??= new SettingsApp());
	}

	/**
	 * Populates local storage with default settings configurations
	 */
	private generateDefaults() {
		if (!this.localStorage.has(SETTINGS_THEME))
			this.localStorage.set(SETTINGS_THEME, this.DEFAULT_THEME);
	}

	/**
	 * @returns saved {@linkcode ThemeValues}
	 */
	public getTheme(): ThemeValues {
		return (
			this.localStorage.get<ThemeValues>(SETTINGS_THEME) ??
			this.DEFAULT_THEME
		);
	}

	/**
	 * Sets local site theme
	 *
	 * @param theme {@linkcode ThemeValues} to change to
	 */
	public setTheme(theme: ThemeValues) {
		this.localStorage.set(SETTINGS_THEME, theme);
	}
}

export default SettingsApp.getInstance();
